#!/bin/sh

case $1 in
"is_loop_partition")	
       /usr/sbin/parted -s /dev/$2 print | grep "Partition Table" | awk '{print $3}' > /tmp/disk_loop_tb
	;;
"get_usb_serialNumber")
	ls $2 |awk -F: '{print $4}'> /tmp/last_num
	;;
"get_disk_volume1")
	/usr/sbin/blkid -d /dev/$2 | grep -o 'LABEL=.*' | awk -F\" '{print $2}' > /tmp/vol_id
	;;
"get_disk_volume2")
	/usr/sbin/blkid -d /dev/$2 -s LABEL |awk -F'LABEL=' '{print $2}' |awk -F'\"' '{print $2}'> /tmp/vol_id
	;;
"get_disk_volume3")
	/bin/echo $(/usr/sbin/parted -s /dev/$2 print | grep "Number" -A16 | sed -n '2,16p' | sed -n $3p | awk 'NF>=6{for(n=6;n<=NF;n++)printf   $n" ";print ""}') > /tmp/vol_id
	;;
"get_disk_filesystem1")
	/usr/sbin/blkid $2 | grep -o 'TYPE=.*' | awk -F\" '{print $2}' > /tmp/vol_id_fs
	;;
"get_disk_filesystem2")
	/usr/sbin/vol_id $2 |grep ID_FS_VERSION | awk -F= '{print $2}' >/tmp/vol_id_fs
	;;
"readycloud_unregister")
	echo "{\"state\":\"0\",\"owner\":\"$2\",\"password\":\"x\"}"|REQUEST_METHOD=PUT PATH_INFO=/api/services/readycloud /www/cgi-bin/readycloud_control.cgi
	;;
"cmd_readycloud_register")
	echo "{\"state\":\"$2\",\"owner\":\"$3\",\"password\":\"$4\"}" |REQUEST_METHOD=PUT PATH_INFO=/api/services/readycloud /www/cgi-bin/readycloud_control.cgi > /dev/console &
	;;
esac
