# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04 # R7800 requires ubuntu 16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Build
      - name: Build firmeware
        run: |
          apt-get update -qq
          apt-get install -qq --no-install-recommends \
            autoconf        \
            build-essential \
            cmake           \
            curl            \
            file            \
            gawk            \
            git             \
            libc6-dev       \
            m4              \
            ncurses-dev     \
            pkg-config      \
            software-properties-common \
            subversion      \
            tzdata \
            unzip \
            wget \
            zip \
            zlib1g \
            zlib1g-dev \
            python \
            python-pip
          pwd
          df
          env
          ls -lh
          #
          # can not compile as root.
          #
          useradd -d `pwd` -s /bin/bash build
          pwd
          ls -lh
          cd r7800
          cp configs/defconfig-r7800 .config
          chown -R build:build `pwd`
          su -m -c "id; pwd; make -j 4 V=99"
          ls -lhR bin
          # the final image is "bin/ipq806x/R7800-V1.0.2.92.img".
